<?php
/**
 * Created by PhpStorm.
 * User: julien
 * Date: 12.01.19
 * Time: 10:56
 */

/**
 * hook_schema
 */
function assessment_schema() {
    /*
    $schema['assessment_question'] = array(
        //'description' => 'Stores the questions of the assessment',
        'fields' => array(
            'aq_id' => array(
                'type' => 'serial',
                'not null' => TRUE,
                //'description' => 'Primary Key aq_id',
            ),
            'question' => array(
                'type' => 'text',
                'size' => 'small',
                'not null' => TRUE,
                //'description' => 'Question text',

            ),
            'primary key' => array('aq_id'),
        ),
    );
    */
    /*
    $schema['assessment_answer_oportunity'] = array(
        'description' => 'Stores the answer oportunities of the assessment question',
        'fields' => array(
            'aao_id' => array(
                'type' => 'serial',
                'not null' => TRUE,
                'description' => 'Primary Key aq_id',
            ),
            'answer_oportunity' => array(
                'type' => 'text',
                'size' => 'small',
                'not null' => TRUE,
                'description' => 'Answer Oportunity',

            ),
            'aq_id' => array(
                'type' => 'int',
                'not null' => TRUE,
                'size' => 'normal',
                'description' => 'Foreign Key to assessment question',
            ),
            'primary key' => array('aao_id'),
        ),
    );
    */
    return $schema;
}