<?php
/**
 * Created by PhpStorm.
 * User: julien
 * Date: 08.05.19
 * Time: 10:27
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function zsb_admin_toolbar() {


  $links['erwartungscheck'] = [
    'title' => t('Erwartungscheck erstellen'),
    'url' => Url::fromRoute('node.add', ['node_type' => 'erwartungscheck']),
  ];

  $links['fachquiz'] = [
    'title' => t('Fachquiz erstellen'),
    'url' => Url::fromRoute('node.add', ['node_type' => 'fachquiz']),
  ];

  $links['studiengang'] = [
    'title' => t('Studiengang erstellen'),
    'url' => Url::fromRoute('node.add', ['node_type' => 'studiengang']),
  ];





  //create the zsb admin toolbar array
  $items['zsb_toolbar'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('ZSB Administration'),
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => [
        'title' => t('ZSB Administration'),
        'class' => ['toolbar-icon', 'toolbar-icon-examples'],
      ],
    ],
    'tray' => [
      '#heading' => t('ZSB Examples'),
      'shortcuts' => [
        '#theme' => 'links__toolbar_example',
        '#links' => $links,
        '#attributes' => [
          'class' => ['toolbar-menu'],
        ],
      ],
    ],


  ];

  return $items;
}